### ISSUE TITLE
Question [Off topic]

### ISSUE THREAD

**Issue by ryanwoltz** [MagicBYang/KeyBoardDesign87#6]
I am sorry to message you on this project. I am wondering if you can share the code solution you mentioned in this post for mapbox spotlight -- https://github.com/peterqliu/threebox/issues/63

I would like to also make a spotlight on 3d map exactly as you did. I have tried many hours with no success. Any help would be greatly appreciated.

Thank you!

**Comment by MagicBYang** [comment]
Sorry I just see the problem now, you solve the Problom already? If not I can share some code when I am not busy.
